[archive_snapshot_from_solaris] fix encryption key check

diff --git a/bin/archive_snapshot_from_solaris b/bin/archive_snapshot_from_solaris
--- a/bin/archive_snapshot_from_solaris
+++ b/bin/archive_snapshot_from_solaris
@@ -9,11 +9,11 @@ identity="${SOLARIS_USER_IDENTITY}"
 
 encryption_key_id="${ENCRYPT_WITH_KEY}"
 
-if [[ -z "$encryption_key_id" ]]; then
+if [[ -n "$encryption_key_id" ]]; then
   if gpg --list-keys --with-colons "recipient_id_or_email" | grep -q "^pub"; then
-      echo "Key is set to $encryption_key_id and does exist in the keyring."
+      echo -e "\e[33mEncryption key is set to $encryption_key_id and does exist in the keyring..\e[0m"
   else
-      echo "Key $encryption_key_id is not found!" >&2
+      echo -e "\e[31mEncryption key $encryption_key_id is not found in keyring!\e[0m" >&2
       exit 1
   fi
 fi
